[project]
name = "sql-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "jupyter>=1.1.1",
    "mcp[cli]>=1.6.0",
    "pymysql>=1.1.1",
]
